parameters:
#    tddv_user.example.class: TDDV\UserBundle\Example

services:
#    tddv_user.example:
#        class: %tddv_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
