<?php

namespace TDDV\CommandeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PredicateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredicateurRepository extends EntityRepository
{
}
